### ISSUE TITLE
Có thể phải triển cho từ điển trên mac được không?

### ISSUE THREAD

**Issue by tuanphamanh91** [catusf/tudien#2]
Mình thấy bộ từ điển này rất hay, nếu mà có thể xuất ra file sử dụng cho mac nữa thì tốt biết bao, cảm ơn tác giả!

**Comment by catusf** [comment]
@tuanphamanh91 từ điển Anh Việt có source là file https://github.com/catusf/tudien/blob/master/dict/TudienAnhVietBeta.opf đó.

Nếu biết format của file từ điển trên Mac thì tạo ra dễ mà. Nhưng có thể nhiều người đã làm việc đó rồi :)
