### ISSUE TITLE
Vấn đề khi tra cứu từ điển trên Kindle

### ISSUE THREAD

**Issue by kiemrong08** [catusf/tudien#4]
Rất cám ơn bạn khi đã tạo ra một từ điển hữu dụng như vậy. Nhưng mình cũng có một vấn đề rất khó chịu là khi tra cứu trên Kindle, nhiều từ tiếng anh trong câu thường theo sau bởi dấu phẩy hoặc dấu chấm, khi mình chạm trên màn hình thì nó sẽ chọn cả từ bao gồm cả dấu phẩy ví dụ `good,` , những lúc này nó sẽ không hiển thị ý nghĩa. Tất nhiên là sẽ có thể kéo để chọn lại nhưng cái thao tác chọn lại đoạn text trên Kindle rất giật khó khăn và đôi khi bạn còn chọn nhầm sang từ khác. Mong bạn có thể xây dựng để nó tra được cả những từ có dấu phẩy đằng sau được không ?

**Comment by catusf** [comment]
@kiemrong08 cái này là hạn chế của software trên Kindle. Về lý thuyết có thể giải quyết bằng cách bổ sung thêm các mục từ (80k) x số dấu câu thường gặp (~5-10). Nhưng như thế thì kích thước từ điển tăng lên nhiều quá.

Có lẽ việc cần làm là feedback cho Amazon để giải quyết ở mức hệ thống.
