### ISSUE TITLE
Thêm dictd format

### ISSUE THREAD

**Issue by nguyentrongquocuet** [catusf/tudien#6]
Mình vừa chuyển sang dùng plato và bọn này chỉ hỗ trợ dictd format, mong bạn build thêm bản của dictd.

**Comment by catusf** [comment]
Nó có phải là format này không? http://[dict.org](http://dict.org/bin/Dict)/bin/Dict

Nếu đúng thì ít ngày nữa mình sẽ add nhe @nguyentrongquocuet

**Comment by nguyentrongquocuet** [comment]
đúng rồi bạn ơi, cái này https://en.wikipedia.org/wiki/DICT#Dict_file_format
Mình thử dùng dicfmt `dictfmt -e --utf8 -s "TuDienAnhVietBeta" -j tudien < TudienAnhVietBeta.txt` sau đó là `dictzip tudien.dict` thì produce được cặp file .index và .dict.dz nhưng thêm vào plato không nhận, chắc là sai format :D

**Comment by nguyentrongquocuet** [comment]
> Nó có phải là format này không? http://[dict.org](http://dict.org/bin/Dict)/bin/Dict
> 
> Nếu đúng thì ít ngày nữa mình sẽ add nhe @nguyentrongquocuet

đúng rồi bạn ơi, cái này https://en.wikipedia.org/wiki/DICT#Dict_file_format
Mình thử dùng dicfmt dictfmt -e --utf8 -s "TuDienAnhVietBeta" -j tudien < TudienAnhVietBeta.txt sau đó là dictzip tudien.dict thì produce được cặp file .index và .dict.dz nhưng thêm vào plato không nhận, chắc là sai format :D

**Comment by catusf** [comment]
@nguyentrongquocuet dictd ok rồi bạn nhé. 

Sorry đợt rồi bận quá nên làm hơi lâu, bạn thông cảm nhé.
